In [1]:
import polars as pl

In [2]:
wd = "C:/Users/Pablo/proyects/data_pipeline_garantias/data/processed/Fotos/"
df_parquet = pl.read_parquet(wd + "Foto_VF_202512.parquet")
df_parquet.shape

(2670258, 57)

In [3]:
df_parquet.describe()

shape: (9, 58)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ BUCKET    ┆ CAMBIO    ┆ MCredito_ ┆ … ┆ fecha_rec ┆ Moneda_Id ┆ pago_or   ┆ recup_or │
│ ---       ┆ ---       ┆ ---       ┆ MM_UDIS   ┆   ┆ up        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.976492e ┆ 2.670258e ┆ 2.670258e ┆ … ┆ 124977    ┆ 218658.0  ┆ 218658.0  ┆ 124977.0 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ null_coun ┆ 693766.0  ┆ 0.0       ┆ 0.0       ┆ … ┆ 2545281   ┆ 2.4516e6  ┆ 2.4516e6  ┆ 2.545281 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e6       │
│ mean      ┆ 1.266006  ┆ 5.001352  ┆ 5.2482e6  ┆ … ┆ 2017-10-1 ┆ 1.013574  ┆ 0.292527  ┆ 0.123897 │
│           ┆           ┆           ┆           ┆   ┆ 7 11:42:0 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 8.788497  ┆           ┆           ┆          │
│ std       ┆ 2.444753  ┆ 1.331417  ┆ 1.1952e7  ┆ … ┆ null      ┆ 0.848072  ┆ 0.653084  ┆ 0.370666 │
│ min       ┆ -1.0      ┆ 1.8244    ┆ 0.025539  ┆ … ┆ 1998-07-3 ┆ 1.0       ┆ -0.0      ┆ -0.012   │
│           ┆           ┆           ┆           ┆   ┆ 0         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 25%       ┆ -1.0      ┆ 3.88741   ┆ 289540.31 ┆ … ┆ 2013-08-0 ┆ 1.0       ┆ 0.013305  ┆ 0.001765 │
│           ┆           ┆           ┆ 5         ┆   ┆ 1         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 50%       ┆ -1.0      ┆ 4.7591    ┆ 982052.5  ┆ … ┆ 2017-12-1 ┆ 1.0       ┆ 0.0739812 ┆ 0.013566 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 75%       ┆ 4.0       ┆ 5.45463   ┆ 4.7680e6  ┆ … ┆ 2022-09-0 ┆ 1.0       ┆ 0.290648  ┆ 0.090303 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ max       ┆ 5.0       ┆ 8.665387  ┆ 9.2351e8  ┆ … ┆ 2025-12-3 ┆ 54.0      ┆ 64.492615 ┆ 25.36396 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆           ┆ 9        │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
fl_foto_final_vf_csv = wd + "Foto_VF_202512.csv"
df_parquet.write_csv(fl_foto_final_vf_csv, float_precision=10, float_scientific=False, datetime_format="%Y/%m/%d %H:%M:%S")

In [5]:
test = (df_parquet
 .select([
     'MGI (MDP)',
     'MONTO CREDITO (MDP)',
     'SALDO (MDP)',
     'MPAGADO (MDP)',
     'PAGADAS',
     'MGI (MDP) Original',
     'MONTOTOTAL (MDP)',
     'RECUPERADOS (MDP)',
     'RESCATADOS (MDP)'
 ])
 .sum().transpose(include_header=True)
 )

In [6]:
with pl.Config(float_precision=4):
    print("\n--- Con Notación Científica Deshabilitada (10 decimales) ---")
    print(test)

--- Con Notación Científica Deshabilitada (10 decimales) ---
shape: (9, 2)
┌─────────────────────┬──────────────┐
│ column              ┆ column_0     │
│ ---                 ┆ ---          │
│ str                 ┆ f64          │
╞═════════════════════╪══════════════╡
│ MGI (MDP)           ┆ 1047087.5811 │
│ MONTO CREDITO (MDP) ┆ 2314926.6675 │
│ SALDO (MDP)         ┆ 133902.8814  │
│ MPAGADO (MDP)       ┆ 64042.0924   │
│ PAGADAS             ┆ 218655.0000  │
│ MGI (MDP) Original  ┆ 835354.1902  │
│ MONTOTOTAL (MDP)    ┆ 19554.7046   │
│ RECUPERADOS (MDP)   ┆ 15502.4140   │
│ RESCATADOS (MDP)    ┆ 4142.8441    │
└─────────────────────┴──────────────┘

In [10]:
df_parquet.describe()

shape: (9, 58)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ BUCKET    ┆ CAMBIO    ┆ MCredito_ ┆ … ┆ fecha_rec ┆ Moneda_Id ┆ pago_or   ┆ recup_or │
│ ---       ┆ ---       ┆ ---       ┆ MM_UDIS   ┆   ┆ up        ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.976492e ┆ 2.670258e ┆ 2.670258e ┆ … ┆ 124977    ┆ 218658.0  ┆ 218658.0  ┆ 124977.0 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ null_coun ┆ 693766.0  ┆ 0.0       ┆ 0.0       ┆ … ┆ 2545281   ┆ 2.4516e6  ┆ 2.4516e6  ┆ 2.545281 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e6       │
│ mean      ┆ 1.266006  ┆ 5.001352  ┆ 5.2482e6  ┆ … ┆ 2017-10-1 ┆ 1.013574  ┆ 0.292527  ┆ 0.123897 │
│           ┆           ┆           ┆           ┆   ┆ 7 11:42:0 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 8.788497  ┆           ┆           ┆          │
│ std       ┆ 2.444753  ┆ 1.331417  ┆ 1.1952e7  ┆ … ┆ null      ┆ 0.848072  ┆ 0.653084  ┆ 0.370666 │
│ min       ┆ -1.0      ┆ 1.8244    ┆ 0.025539  ┆ … ┆ 1998-07-3 ┆ 1.0       ┆ -0.0      ┆ -0.012   │
│           ┆           ┆           ┆           ┆   ┆ 0         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 25%       ┆ -1.0      ┆ 3.88741   ┆ 289540.31 ┆ … ┆ 2013-08-0 ┆ 1.0       ┆ 0.013305  ┆ 0.001765 │
│           ┆           ┆           ┆ 5         ┆   ┆ 1         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 50%       ┆ -1.0      ┆ 4.7591    ┆ 982052.5  ┆ … ┆ 2017-12-1 ┆ 1.0       ┆ 0.0739812 ┆ 0.013566 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ 75%       ┆ 4.0       ┆ 5.45463   ┆ 4.7680e6  ┆ … ┆ 2022-09-0 ┆ 1.0       ┆ 0.290648  ┆ 0.090303 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ max       ┆ 5.0       ┆ 8.665387  ┆ 9.2351e8  ┆ … ┆ 2025-12-3 ┆ 54.0      ┆ 64.492615 ┆ 25.36396 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆           ┆ 9        │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘